repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: poetry run ruff check
        language: system
        types: [ python ]
        pass_filenames: false
        args: [ --fix ]
      - id: ruff-fmt
        name: ruff-fmt
        entry: poetry run ruff format
        language: system
        types: [ python ]
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: poetry run mypy .
        language: system
        types: [python]
        pass_filenames: false
      - id: poetry-check
        name: poetry-check
        entry: poetry check
        language: python
        language_version: python3
        pass_filenames: false
        files: 'pyproject\.toml$'
